version: '3.7'

services:
  api:
    container_name: clips-api
    hostname: clips-api
    image: clips-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3333:3333
      - 9229:9229
    command: npm run start:api
